# -*- coding: utf-8 -*-
"""
Django settings for colaborador project.

Generated by 'django-admin startproject' using Django 1.8.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

###############################################################################################################
############# adicionado para ler arquivo externo com configuraçãoes sensíveis e sigilosas ################
###############################################################################################################
# definir nome do arquivo para settings.conf
SETTINGS_EXTRA = 'settings.conf'


import readconf
readconf.read_conf(os.path.join(os.path.dirname(os.path.dirname(__file__)), SETTINGS_EXTRA))
###############################################################################################################


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = '2mzi2-0yypz*k^a0lo)q*0rb(&xisqr8infd(&e97#x1p(&p%+'
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
DEBUG = os.environ.get('DEBUG')


# ALLOWED_HOSTS = []
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost').split(',')

# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'colaborador.userprofile',
    'colaborador.banco',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'colaborador.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'colaborador.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

# LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

SESSION_EXPIRE_AT_BROWSER_CLOSE = True

AUTHENTICATION_BACKENDS = (
    'colaborador.ldapauth.LDAPBackend',
    'django.contrib.auth.backends.ModelBackend',
)

# ldap settings for ldap backend
import ldap

LDAP_DEBUG = True

#AD
LDAP_SERVER_URI = os.environ.get('LDAP_SERVER_URI')
LDAP_PREBINDDN = os.environ.get('LDAP_PREBINDDN')
LDAP_PREBINDPW = os.environ.get('LDAP_PREBINDPW')
LDAP_SEARCHDN = os.environ.get('LDAP_SEARCHDN')

LDAP_SEARCH_FILTER = 'cn=%s' #or sAMAccountName
LDAP_SCOPE = ldap.SCOPE_SUBTREE
LDAP_UPDATE_FIELDS = True

#Required unless LDAP_FULL_NAME is set:
LDAP_FIRST_NAME = 'givenName'
LDAP_LAST_NAME = 'sn'

#Optional Settings:
LDAP_FULL_NAME = 'displayName'
#LDAP_GID -- string, LDAP attribute to get group name/number from
#LDAP_SU_GIDS -- list of strings, group names/numbers that are superusers
#LDAP_STAFF_GIDS -- list of strings, group names/numbers that are staff
LDAP_EMAIL = 'mail'